export { default as grassImg } from "./grass.jpg";
export { default as glassImg } from "./glass.png";
export { default as dirtImg } from "./dirt.jpg";
export { default as logImg } from "./log.jpg";
export { default as woodImg } from "./wood.png";
export { default as stoneImg } from "./stone.png";
export { default as diamondImg } from "./diamond.png";
export { default as steelImg } from "./steel.png";
export { default as goldImg } from "./gold.png";
